### ISSUE TITLE
CUDA out of memory，even set batch_size to 1

### ISSUE THREAD

**Issue by Mao-JianGuo** [NVIDIA/waveglow#185]
RuntimeError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 8.00 GiB total capacity; 5.69 GiB already allocated; 4.04 MiB free; 5.88 GiB reserved in total by PyTorch)

i have set batch_size to 1, but it still occur oom

**Comment by mathematiguy** [comment]
What sort of GPU do you have? It seems the most likely explanation is that you have another process that is using the GPU memory. If you set `"fp16_run": true` in `config.json` this also reduces memory use.

**Comment by gzfffff** [comment]
I also have this question, my GPU is nvidia P100, and I'm sure that there is no other process that is using the GPU. I think it is because the model is too big, so I use apex.amp to try to train the model and it works.

**Comment by EuphoriaCelestial** [comment]
I can run with batch_size=1 on 1050ti 4GB, you should check your system for running processes

**Comment by rafaelvalle** [comment]
You can decrease the segment length.
Closing due to inactivity.

**Comment by EuphoriaCelestial** [comment]
> You can decrease the segment length if running out of memory. You should be able to fit batch size 1 on a 8GB GPU.
> Closing due to inactivity.

in case I have many VRAM left, should I increase segment length?
how does segment length affect accuracy, inference speed, training speed?

**Comment by rafaelvalle** [comment]
We haven't explored the effect of changing segment length on output quality.
Shorter segment lengths will result in more padded values, which is not helpful for optimization.

**Comment by brentcty-2020** [comment]
Was this ever resolved. I'm getting this on a RTX 2070 Super 8GB. I've tried 1 BS and 1,000 segment size and still get the same error. I'm also seeing the following warning...Could this be related. I found I needed to upgrade the NGC docker version of PyTorch to be compatible with my Cuda version. Should we be using a more recent NGC?

Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ImportError('/opt/conda/lib/python3.6/site-packages/amp_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv',)

**Comment by shangeth** [comment]
In Google Colab, with a batch size of 1, it gives out of memory error for an audio 5 seconds long. 

```
waveglow = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_waveglow', model_math='fp32')

waveglow = waveglow.remove_weightnorm(waveglow)
waveglow = waveglow.to('cuda')
waveglow.eval()

audio = waveglow.infer(mel.cuda())
```


Before the model => GPU Memory = 1100MiB / 15109MiB
After defining the model => GPU Memory = 15046MiB / 15109MiB
